# Generated by Django 4.0 on 2021-12-24 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Webdevelopment_Details',
            fields=[
                ('did', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20)),
                ('age', models.IntegerField()),
                ('phone_no', models.BigIntegerField(unique=True)),
                ('gender', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'Webdevelopment_Details',
                'verbose_name_plural': 'Webdevelopment_Detailss',
            },
        ),
    ]
